#!/usr/bin/env python3
import itertools
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

IN_021 = ROOT / "artifacts/json/native_g60_anchor_candidate_feature_audit_021.v1.json"

OUT_JSON = ROOT / "artifacts/json/native_g60_anchor_rank_fingerprint_law_022.v1.json"
OUT_NOTE = ROOT / "notes/native_g60_anchor_rank_fingerprint_law_022.md"

STATES = ["O0", "O1", "B0", "B1"]


def load_json(path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def bits(state):
    if state == "O0":
        return 0, 0
    if state == "O1":
        return 0, 1
    if state == "B0":
        return 1, 0
    if state == "B1":
        return 1, 1
    raise ValueError(state)


def eval_poly(coeffs, b, r):
    # integer polynomial basis: 1, b, r, b*r
    c0, cb, cr, cbr = coeffs
    return c0 + cb*b + cr*r + cbr*b*r


def main():
    a021 = load_json(IN_021)
    if not a021.get("all_checks_pass"):
        raise SystemExit("021 all_checks_pass is not true")

    targets = {}
    rows = []

    for state in STATES:
        p = a021["per_state"][state]
        b, r = bits(state)
        target_rank = int(p["observed_rank_by_best_support_sum_desc"])
        targets[state] = target_rank
        rows.append({
            "state": state,
            "shell_bit": b,
            "rank_bit": r,
            "target_rank": target_rank,
            "candidate_count": int(p["candidate_count"]),
            "observed_support_sum": int(p["observed_support_sum"]),
        })

    exact_integer_affine_laws = []
    search_range = range(-20, 21)

    for coeffs in itertools.product(search_range, repeat=4):
        preds = {
            row["state"]: eval_poly(coeffs, row["shell_bit"], row["rank_bit"])
            for row in rows
        }
        if all(preds[state] == targets[state] for state in STATES):
            exact_integer_affine_laws.append({
                "basis": "1,b,r,b*r",
                "coeffs": list(coeffs),
                "formula": f"{coeffs[0]} + {coeffs[1]}*b + {coeffs[2]}*r + {coeffs[3]}*b*r",
            })

    # Keep smallest by L1 norm for readability.
    exact_integer_affine_laws.sort(key=lambda x: (sum(abs(c) for c in x["coeffs"]), x["coeffs"]))
    smallest = exact_integer_affine_laws[:20]

    # Direct derived law from four points, no search needed:
    # f(0,0)=2, f(0,1)=4, f(1,0)=9, f(1,1)=10
    # c0=2, cr=2, cb=7, cbr=-1
    canonical_coeffs = [2, 7, 2, -1]
    canonical_predictions = {
        row["state"]: eval_poly(canonical_coeffs, row["shell_bit"], row["rank_bit"])
        for row in rows
    }

    checks = {
        "feature_audit_021_checks_pass": bool(a021.get("all_checks_pass")),
        "target_rank_profile_is_2_4_9_10": [targets[s] for s in STATES] == [2, 4, 9, 10],
        "canonical_bit_law_matches_all_states": all(canonical_predictions[s] == targets[s] for s in STATES),
        "at_least_one_exact_integer_law_found": len(exact_integer_affine_laws) > 0,
    }

    result = {
        "status": "native_g60_anchor_rank_fingerprint_law_recorded",
        "audit_id": "022",
        "inputs": {
            "feature_audit_021": str(IN_021),
        },
        "target_rank_profile": targets,
        "rows": rows,
        "canonical_basis": "1,b,r,b*r",
        "canonical_coeffs": canonical_coeffs,
        "canonical_formula": "rank = 2 + 7*b + 2*r - b*r",
        "canonical_predictions": canonical_predictions,
        "exact_integer_affine_law_count": len(exact_integer_affine_laws),
        "smallest_exact_integer_affine_laws": smallest,
        "checks": checks,
        "theorem_pass": all(checks.values()),
        "claim": (
            "The observed support-rank fingerprint from artifact 021 is generated by the two local state bits: "
            "rank = 2 + 7*b + 2*r - b*r."
        ),
        "interpretation": (
            "The candidate rank fingerprint 2,4,9,10 is not merely four unrelated labels. It is a compact two-bit law. "
            "This gives a possible rank-target selector for the observed anchor paths, but the law is still fitted to the "
            "four observed state ranks and needs independent native/provenance validation."
        ),
        "boundary": (
            "This derives a compact bit law for the observed support-rank fingerprint. It does not prove that this rank law "
            "is native, does not derive anchor residue sets, does not derive a validated anchor path selector theorem, does not "
            "test station fields, does not select unique relay mediators, does not derive the full role-labeled shared_B universe, "
            "and does not close Gap A."
        ),
    }

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_NOTE.parent.mkdir(parents=True, exist_ok=True)

    OUT_JSON.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = []
    lines.append("# Native G60 anchor rank fingerprint law 022")
    lines.append("")
    lines.append("Status: " + result["status"])
    lines.append("")
    lines.append("## Claim")
    lines.append("")
    lines.append(result["claim"])
    lines.append("")
    lines.append("## Result")
    lines.append("")
    lines.append("- theorem_pass: `" + str(result["theorem_pass"]) + "`")
    lines.append("- target_rank_profile: `" + str(targets) + "`")
    lines.append("- canonical_formula: `" + result["canonical_formula"] + "`")
    lines.append("- canonical_predictions: `" + str(canonical_predictions) + "`")
    lines.append("- exact_integer_affine_law_count: `" + str(len(exact_integer_affine_laws)) + "`")
    lines.append("")
    lines.append("## Rows")
    lines.append("")
    for row in rows:
        lines.append(
            "- "
            + row["state"]
            + ": bits `("
            + str(row["shell_bit"])
            + ", "
            + str(row["rank_bit"])
            + ")`, target_rank `"
            + str(row["target_rank"])
            + "`, candidate_count `"
            + str(row["candidate_count"])
            + "`"
        )
    lines.append("")
    lines.append("## Checks")
    lines.append("")
    for k, v in checks.items():
        lines.append("- " + k + ": `" + str(v) + "`")
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append(result["interpretation"])
    lines.append("")
    lines.append("## Boundary")
    lines.append("")
    lines.append(result["boundary"])
    lines.append("")

    OUT_NOTE.write_text("\n".join(lines), encoding="utf-8")

    print("wrote", OUT_JSON)
    print("wrote", OUT_NOTE)
    print("status", result["status"])
    print("theorem_pass", result["theorem_pass"])
    print("canonical_formula", result["canonical_formula"])
    print("canonical_predictions", canonical_predictions)
    print("exact_integer_affine_law_count", len(exact_integer_affine_laws))


if __name__ == "__main__":
    main()
